# Episodic Tagging Background

### Record reading responses [here](https://docs.google.com/spreadsheets/d/1rvgFBIHkx0lYMrKbI0QLT9KvEoggyIo54hlFbpklYrU/edit?usp=sharing)

Atance, C. M., & O’Neill, D. K. (2001). Episodic future thinking. Trends in Cognitive Sciences, 5(12), 533–539.

Atance, C. M., & O’Neill, D. K. (2005). The emergence of episodic future thinking in humans. Learning and Motivation. Retrieved from https://www.sciencedirect.com/science/article/pii/S0023969005000226

Benoit, R. G., Davies, D. J., & Anderson, M. C. (2016). Reducing future fears by suppressing the brain mechanisms underlying episodic simulation. Proceedings of the National Academy of Sciences of the United States of America, 113(52), E8492–E8501.

Bisby, J. A., Horner, A. J., Bush, D., & Burgess, N. (2018). Negative emotional content disrupts the coherence of episodic memories. Journal of Experimental Psychology. General, 147(2), 243–256.

Bowden, V. K., Visser, T. A. W., & Loft, S. (2017). Forgetting induced speeding: Can prospective memory failure account for drivers exceeding the speed limit? Journal of Experimental Psychology. Applied, 23(2), 180–190.

Bulley, A., & Gullo, M. J. (2017). The influence of episodic foresight on delay discounting and demand for alcohol. Addictive Behaviors, 66, 1–6.

Bulley, A., Henry, J., & Suddendorf, T. (2016). Prospection and the present moment: The role of episodic foresight in intertemporal choices between immediate and delayed rewards. Review of General Psychology: Journal of Division 1, of the American Psychological Association, 20(1), 29.

Campbell, K. L., Madore, K. P., Benoit, R. G., Thakral, P. P., & Schacter, D. L. (2018). Increased hippocampus to ventromedial prefrontal connectivity during the construction of episodic future events. Hippocampus, 28(2), 76–80.

Daniel, T. O., Said, M., Stanton, C. M., & Epstein, L. H. (2015). Episodic future thinking reduces delay discounting and energy intake in children. Eating Behaviors, 18, 20–24.

Doll, B. B., Duncan, K. D., Simon, D. A., Shohamy, D., & Daw, N. D. (2015). Model-based choices involve prospective neural activity. Nature Neuroscience, 18(5), 767–772.

Hu, X., Kleinschmidt, H., Martin, J. A., Han, Y., Thelen, M., Meiberth, D., … Weber, B. (2016). A Reduction in Delay Discounting by Using Episodic Future Imagination and the Association with Episodic Memory Capacity. Frontiers in Human Neuroscience, 10, 663.

Jing, H. G., Madore, K. P., & Schacter, D. L. (2016). Worrying about the future: An episodic specificity induction impacts problem solving, reappraisal, and well-being. Journal of Experimental Psychology. General, 145(4), 402–418.

Kaplan, B. A., & Reed, D. D. (2016). Effects of episodic future thinking on discounting: Personalized age‐progressed pictures improve risky long‐term health decisions. Journal of Applied. Retrieved from http://onlinelibrary.wiley.com/doi/10.1002/jaba.277/full

Kaplan, R., King, J., Koster, R., Penny, W. D., Burgess, N., & Friston, K. J. (2017). The Neural Representation of Prospective Choice during Spatial Planning and Decisions. PLoS Biology, 15(1), e1002588.

Madore, K. P., & Schacter, D. L. (2014). An episodic specificity induction enhances means-end problem solving in young and older adults. Psychology and Aging. Retrieved from http://psycnet.apa.org/record/2014-45575-001

May, F. (2017). The Effect of Future Event Markers on Intertemporal Choice Is Moderated by the Reliance on Emotions versus Reason to Make Decisions. The Journal of Consumer Research, 44(2), 313–331.

Murty, V. P., FeldmanHall, O., & Hunter, L. E. (2016). Episodic memories predict adaptive value-based decision-making. Journal of. Retrieved from http://psycnet.apa.org/record/2016-13814-001

Murty, V. P., FeldmanHall, O., Hunter, L. E., Phelps, E. A., & Davachi, L. (2016). Episodic memories predict adaptive value-based decision-making. Journal of Experimental Psychology. General, 145(5), 548–558.

Peters, J., & Büchel, C. (2010). Episodic future thinking reduces reward delay discounting through an enhancement of prefrontal-mediotemporal interactions. Neuron, 66(1), 138–148.

Sasse, L. K., Peters, J., Büchel, C., & Brassen, S. (2015). Effects of prospective thinking on intertemporal choice: The role of familiarity. Human Brain Mapping, 36(10), 4210–4221.

Schacter, D. L., Benoit, R. G., De Brigard, F., & Szpunar, K. K. (2015). Episodic future thinking and episodic counterfactual thinking: intersections between memory and decisions. Neurobiology of Learning and Memory, 117, 14–21.

Spreng, R. N., Mar, R. A., & Kim, A. S. N. (2009). The common neural basis of autobiographical memory, prospection, navigation, theory of mind, and the default mode: a quantitative meta-analysis. Journal of Cognitive Neuroscience, 21(3), 489–510.

St-Amand, D., Sheldon, S., & Otto, A. R. (2018). Modulating Episodic Memory Alters Risk Preference during Decision-making. Journal of Cognitive Neuroscience, 1–9.

Stein, J. S., Sze, Y. Y., Athamneh, L., Koffarnus, M. N., Epstein, L. H., & Bickel, W. K. (2017). Think fast: rapid assessment of the effects of episodic future thinking on delay discounting in overweight/obese participants. Journal of Behavioral Medicine, 40(5), 832–838.

Sze, Y. Y., Stein, J. S., Bickel, W. K., Paluch, R. A., & Epstein, L. H. (2017). Bleak Present, Bright Future: Online Episodic Future Thinking, Scarcity, Delay Discounting, and Food Demand. Clinical Psychological Science, 5(4), 683–697.

Szpunar, K. K. (2010). Episodic Future Thought: An Emerging Concept. Perspectives on Psychological Science: A Journal of the Association for Psychological Science, 5(2), 142–162.

Szpunar, K. K., & Radvansky, G. A. (2016). Cognitive approaches to the study of episodic future thinking. Quarterly Journal of Experimental Psychology , 69(2), 209–216.

Thakral, P. P., Benoit, R. G., & Schacter, D. L. (2017). Characterizing the role of the hippocampus during episodic simulation and encoding. Hippocampus, 27(12), 1275–1284.
